name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
#        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: FedericoCarboni/setup-ffmpeg@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn
      - run: yarn workspace reactive-video build
      - run: npm run lint
      - run: npm test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: artifact
          path: |
            reactive-video-assets/test-output/
            reactive-video-assets/test-image-snapshots/__diff_output__/
